api/urls.py
from django.urls import path

from .views import *

urlpatterns = [
	path('drivers/<int:pk>/comments/', comments),
	path('drivers/<int:pk>', DriverDetailView.as_view()),
    path('drivers/', driver_list),
    path('teams/', team_list),
    ]

formula_one/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
    path('', include('main.urls', namespace='')),
    path('social/', include('social_django.urls', namespace='social')),
    path('api/', include('api.urls')),
]


if settings.DEBUG:
    # Отключение кеширования статичных файлов
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

main/urls.py
from django.urls import path


from .views import *

app_name = 'main'

urlpatterns = [
	path('accounts/register/activate/<str:sign>/', user_activate, name='register_activate'),
	path('accounts/register/done', RegisterDoneView.as_view(), name='register_done'),
	path('accounts/register', RegisterUserView.as_view(), name='register'),
	path('accounts/password/reset/<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(), 
									name='password_reset_confirm'),
	path('accounts/password/reset/complete/', UserPasswordResetCompleteView.as_view(), 
									name='password_reset_complete'),
	path('accounts/password/reset/done/', UserPasswordResetDoneView.as_view(),
									name='password_reset_done'),
	path('accounts/password/reset/', UserPasswordResetView.as_view(), 
									name='password_reset'),
	path('accounts/password/change', UserPasswordChangeView.as_view(), name='password_change'),
	path('accounts/profile/delete/', DeleteUserView.as_view(), name='profile_delete'),
	path('accounts/profile/change', ChangeUserInfoView.as_view(), name='profile_change'),
	path('accounts/profile/', profile, name='profile'),
	path('accounts/logout/', UserLogoutView.as_view(), name='logout'),
	path('accounts/login/', UserLoginView.as_view(), name='login'),
	path('drivers/<int:pk>/', driver_detail, name='driver_detail'),
	path('drivers/', by_drivers, name='by_drivers'),
	path('teams/<int:pk>/', team_detail, name='team_detail'),
	path('teams/', by_teams, name='by_teams'),
	path('tracks/<int:pk>/', track_detail, name='track_detail'),
	path('tracks/', by_tracks, name='by_tracks'),
	path('<str:page>/', other_page, name='other'),
	path('', index, name='index'),
	]

main/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError
from captcha.fields import CaptchaField

from .models import AdvUser, user_registrated, Comment

class ChangeUserInfoForm(forms.ModelForm):
	"""Форма для изменения личных данных"""
	email = forms.EmailField(required=True, label='Адрес электронной почты')

	class Meta:
		model = AdvUser
		fields = ('username', 'email', 'first_name', 'last_name', 'send_messages', 'favorite_team')


class RegisterUserForm(forms.ModelForm):
	"""Форма для регистрации нового пользователя"""		
	email = forms.EmailField(required=True, label='Адрес электронной почты')
	password1 = forms.CharField(label='Пароль', widget = forms.PasswordInput,
								help_text=password_validation.password_validators_help_text_html())
	password2 = forms.CharField(label='Пароль(Повторно)', widget = forms.PasswordInput,
								help_text='Введите пароль еще раз')

	def clean_password1(self):
		"""валидация пароля первого поля"""
		password1 = self.cleaned_data['password1']
		if password1:
			password_validation.validate_password(password1)
		return password1	

	def clean(self):
		"""Проверка на идентичность обоих паролей"""
		super().clean()
		password1 = self.cleaned_data['password1']
		password2 = self.cleaned_data['password2']
		if password1 and password2 and password1 != password2:
			errors = {'password2': ValidationError('Введенные пароли не совпадают', code='password_mismatch')}
			raise ValidationError(errors)

	def save(self, commit=True):
		"""Сохранение пользователя"""
		user = super().save(commit=False)
		user.set_password(self.cleaned_data['password1'])
		# Активный пользователь?
		user.is_active = False
		# Выполнил ли пользователь процедуру активации?
		user.is_activated = False

		if commit:
			user.save()

		# отправка сигнала для отправки письма об активации
		user_registrated.send(RegisterUserForm, instance=user)

		return user	

	class Meta:
		model = AdvUser
		fields = ('username', 'email', 'password1', 'password2', 'first_name', 
				  'last_name', 'send_messages', 'favorite_team')	


class UserCommentForm(forms.ModelForm):
	"""Форма для занесения комментариев
		зарег. пользователям"""
	class Meta:
		model = Comment
		exclude = ('is_active',)
		widgets = {'driver' : forms.HiddenInput}


class GuestCommentForm(forms.ModelForm):
	"""Форма для занесения комментариев
		гостями"""		
	captcha = CaptchaField(label='Введите текст с картинки', 
							error_messages={'invalid':'Неправильный текст'})
	class Meta:
		model = Comment
		exclude = ('is_active',)
		widgets = {'driver' : forms.HiddenInput}							
		

main/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from django.template import TemplateDoesNotExist
from django.template.loader import get_template
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordResetDoneView
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView, PasswordResetCompleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import UpdateView, CreateView, DeleteView, FormView
from django.views.generic.base import TemplateView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.core.signing import BadSignature
from django.contrib.auth import logout
from django.contrib import messages
from django.core.paginator import Paginator
from django.views.decorators.cache import cache_page

from .models import AdvUser, Driver, Team, Track, Comment, Post
from .forms import ChangeUserInfoForm, RegisterUserForm, UserCommentForm, GuestCommentForm
from .utilities import signer
 



def index(request):
	"""Главная страница"""
	posts = Post.objects.all()[:10]
	drivers = Driver.objects.filter(is_active=True).order_by('-scores_season')
	teams = Team.objects.filter(is_active=True).order_by('-scores_season')
	context = {'posts': posts, 'drivers': drivers, 'teams': teams}
	return render(request, 'main/index.html', context)


def other_page(request, page):
	try:
		template = get_template('main/' + page + '.html')
	except TemplateDoesNotExist:
		raise Http404	
	return HttpResponse(template.render(request=request))	


class UserLoginView(LoginView):
	"""Странциа входа"""
	template_name = 'main/login.html'


# Декоратор
# Допускает к странице только пользователей,
# выполнивших вход
@login_required
def profile(request):
	"""Профиля"""
	return render(request, 'main/profile.html')


class UserLogoutView(LoginRequiredMixin, LogoutView):
	"""Выход с сайта"""
	template_name = 'main/logout.html'


class ChangeUserInfoView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
	"""Правки личных данных"""
	model = AdvUser
	template_name = 'main/change_user_info.html'
	form_class = ChangeUserInfoForm
	success_url = reverse_lazy('main:profile')
	success_message = 'Личные данные пользователя изменены'

	def dispatch(self, request, *args, **kwargs):
		self.user_id = request.user.pk
		return super().dispatch(request, *args, **kwargs)

	def get_object(self, queryset=None):
		if not queryset:
			queryset = self.get_queryset()
		return get_object_or_404(queryset, pk=self.user_id)	


class UserPasswordChangeView(SuccessMessageMixin, LoginRequiredMixin, PasswordChangeView):
	"""Изменения пароля"""
	template_name = 'main/password_change.html'
	success_url = reverse_lazy('main:profile')
	success_message = 'Пароль изменен'


class RegisterUserView(CreateView):
	"""Регистрации"""
	model = AdvUser
	template_name = 'main/register_user.html'
	form_class = RegisterUserForm
	success_url = reverse_lazy('main:register_done')


class RegisterDoneView(TemplateView):
	"""Сообщение об успешной регистрации"""	
	template_name = 'main/register_done.html'


def user_activate(request, sign):
	"""Активация нового пользователя"""
	try:
		username = signer.unsign(sign)
	except BadSignature:
		return render(request, 'main/bad_signature.html')
	user = get_object_or_404(AdvUser, username=username)
	
	if user.is_activated:
		template = 'main/user_is_activated.html'
	else:
		template = 'main/activation_done.html'
		user.is_active = True
		user.is_activated = True
		user.save()

	return render(request, template)		


class DeleteUserView(DeleteView):
	"""Удаление пользователя"""	
	model = AdvUser
	template_name = 'main/delete_user.html'
	success_url = reverse_lazy('main:index')

	def dispatch(self, request, *args, **kwargs):
		self.user_id = request.user.pk
		return super().dispatch(request, *args, **kwargs)

	def post(self, request, *args, **kwargs):
		logout(request)
		messages.add_message(request, messages.SUCCESS, 'Пользователь удален')
		return super().post(request, *args, **kwargs)

	def get_object(self, queryset=None):
		if not queryset:
			queryset = self.get_queryset()
		return get_object_or_404(queryset, pk=self.user_id)		


class UserPasswordResetView(PasswordResetView):
	"""Отправка письма для сброса пароля"""
	template_name = 'main/password_reset.html'
	subject_template_name = 'email/reset_subject.txt'
	email_template_name = 'email/reset_email.html'
	success_url = reverse_lazy('main:password_reset_done')
	

class UserPasswordResetDoneView(PasswordResetDoneView):
	"""Уведомление об отправке письма"""
	template_name = 'main/email_sent.html'


class UserPasswordResetConfirmView(PasswordResetConfirmView):
	"""Сброс пароля"""
	template_name = 'main/password_reset_confirm.html'
	success_url = reverse_lazy('main:password_reset_complete')


class UserPasswordResetCompleteView(PasswordResetCompleteView):
	"""Уведомление об успешной смене пароля"""
	template_name = 'main/password_reset_complete.html'



def by_drivers(request):
	"""Вывод всех пилотов"""
	drivers = Driver.objects.all()
	# Использование пагинатора
	paginator = Paginator(drivers, 8)
	if 'page' in request.GET:
		page_num = request.GET['page']
	else:
		page_num = 1
	page = paginator.get_page(page_num)

	context = {'page': page, 'drivers': page.object_list}
	return render(request, 'main/by_drivers.html', context)

# кеширование страницы 600 сек
@cache_page(600)
def by_teams(request):
	"""Вывод всех команд"""
	teams = Team.objects.all()
	context = {'teams': teams}
	return render(request, 'main/by_teams.html', context)



def by_tracks(request):
	"""Вывод всех трасс"""
	tracks = Track.objects.all()
	context = {'tracks': tracks}
	return render(request, 'main/by_tracks.html', context)



def team_detail(request, pk):
	"""Подробно о команде"""
	team = get_object_or_404(Team, pk=pk)
	drivers = Driver.objects.filter(team=pk)
	context = {'team': team, 'drivers': drivers}
	return render(request, 'main/team_detail.html', context)



def driver_detail(request, pk):
	"""Подробно о гонщике"""
	driver = get_object_or_404(Driver, pk=pk)
	comments = Comment.objects.filter(driver=pk, is_active=True)

	#заносим в поле driver ключ текущего пилота
	initial = {'driver': driver.pk}

	# Если пользователь авторизован, его имя заносим как автора коммментария
	if request.user.is_authenticated:
		initial['author'] = request.user.username
		form_class = UserCommentForm
	else:
		form_class = GuestCommentForm

	form = form_class(initial=initial)
	if request.method == 'POST':
		c_form = form_class(request.POST)
		if c_form.is_valid():
			c_form.save()
			messages.add_message(request, messages.SUCCESS, 'Комментарий добавлен')

		else:
			form = c_form
			messages.add_message(request, messages.WARNING, 'Комментарий не добавлен')

	context = {'driver': driver, 'comments': comments, 'form': form}
	return render(request, 'main/driver_detail.html', context)	
	


def track_detail(request, pk):
	"""Подробно о трассе"""
	track = get_object_or_404(Track, pk=pk)
	context = {'track': track}
	return render(request, 'main/track_detail.html', context)

main/templates/layout/basic.html
{% load bootstrap4 %}
{% load static %}

<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="Content-Type"
		content="text/html"; charset="utf-8">
		<meta name="viewport"
		content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<title>{% block title %}Новости{% endblock %}</title>
		{% bootstrap_css %}
		<link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}">
		{% bootstrap_javascript jquery='slim' %}
	</head>
<!-------------------------------------------------------------------------------------->

	<body class="container-fluid">
		<header class="mb-4">
			<h1 class="display-1 text-center">Formula One</h1>
		</header>


<!--------------------------Панель навигации-------------------------------------------->

		<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
		  
			<div class="collapse navbar-collapse" id="navbarText">
				<ul class="navbar-nav mr-auto">

					<li class="nav-item active">
						<a class="nav-link" href="{% url 'main:index' %}">Новости</a>
					</li>

					<li class="nav-item active">
						<a class="nav-link" href="{% url 'main:by_drivers' %}">Пилоты</a>
					</li>

					<li class="nav-item active">
						<a class="nav-link" href="{% url 'main:by_teams' %}">Команды</a>
					</li>

					<li class="nav-item active">
						<a class="nav-link" href="{% url 'main:by_tracks' %}">Трассы</a>
					</li>

				</ul>

			</div>


<!-----------Меню профиля, если пользователь авторизован------------ -->

			<div class="row">
				<ul class="col nav justify-content-end border">

					{% if user.is_authenticated %}
					<li class="nav-item dropdown">

						<a  class="nav-link dropdown-toggle" 
							data-toggle="dropdown" 
							href="#"
							role="button"
							aria-haspopup="true"
							aria-expanded="false">Профиль</a>

						<div class="dropdown-menu">
							<a 	class="dropdown-item" 
								href="{% url 'main:profile' %}">Избранное</a>

							<a  class="dropdown-item" 
								href="{% url 'main:profile_change' %}">Изменить личные данные</a>

							<a  class="dropdown-item" 
								href="{% url 'main:password_change' %}">Изменить пароль</a>

							<a  class="dropdown-item" 
								href="{% url 'main:password_reset' %}">Сбросить пароль</a>	

							<div class="dropdown-divider"></div>

								<a  class="dropdown-item" 
									href="{% url 'main:logout' %}">Выйти</a>

							<div class="dropdown-divider"></div>

							<a  class="dropdown-item" 
								href="{% url 'main:profile_delete' %}">Удалить</a>
						</div>

					</li>

					<!-----------Если не авторизован------------ -->
					{% else %}

						<a href="{% url 'social:begin' 'vk-oauth2' %}">
							<img src="..\..\static\main\social.png" width='50' alt="Войти через ВК">
						</a>

					<li class="nav-item">
						<a  class="nav-link" 
							href="{% url 'main:login' %}">Вход</a>
					</li>

					{% endif %}

					<li class="nav-item">

						<a  class="nav-link" 
							href="{% url 'main:register' %}">Регистрация</a>

				</ul>		
			</div>


		</nav>



<!--------------------------------Секция основного контента--------------------------------- -->
		<section class="col  py-2">

			{% bootstrap_messages %}
			{% block content %}
			{% endblock %}

		</section>

			
<!--------------------------------------------------------------------------------------------- -->
		<footer class="mt-3"> 
			<a class="font-italic" href="{% url 'main:other' page='about' %}">О сайте</a>
			<p class="text-right font-italic">&copy; Семенов Максим, 2020 г.</p>
		</footer>


	</body>
</html>