api/urls.py
from django.urls import path

from .views import *

urlpatterns = [
	path('drivers/<int:pk>/comments/', comments),
	path('drivers/<int:pk>', DriverDetailView.as_view()),
    path('drivers/', driver_list),
    path('teams/', team_list),
    ]

formula_one/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
    path('', include('main.urls', namespace='')),
    path('social/', include('social_django.urls', namespace='social')),
    path('api/', include('api.urls')),
]


if settings.DEBUG:
    # Отключение кеширования статичных файлов
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

main/urls.py
from django.urls import path


from .views import *

app_name = 'main'

urlpatterns = [
	path('accounts/register/activate/<str:sign>/', user_activate, name='register_activate'),
	path('accounts/register/done', RegisterDoneView.as_view(), name='register_done'),
	path('accounts/register', RegisterUserView.as_view(), name='register'),
	path('accounts/password/reset/<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(), 
									name='password_reset_confirm'),
	path('accounts/password/reset/complete/', UserPasswordResetCompleteView.as_view(), 
									name='password_reset_complete'),
	path('accounts/password/reset/done/', UserPasswordResetDoneView.as_view(),
									name='password_reset_done'),
	path('accounts/password/reset/', UserPasswordResetView.as_view(), 
									name='password_reset'),
	path('accounts/password/change', UserPasswordChangeView.as_view(), name='password_change'),
	path('accounts/profile/delete/', DeleteUserView.as_view(), name='profile_delete'),
	path('accounts/profile/change', ChangeUserInfoView.as_view(), name='profile_change'),
	path('accounts/profile/', profile, name='profile'),
	path('accounts/logout/', UserLogoutView.as_view(), name='logout'),
	path('accounts/login/', UserLoginView.as_view(), name='login'),
	path('drivers/<int:pk>/', driver_detail, name='driver_detail'),
	path('drivers/', by_drivers, name='by_drivers'),
	path('teams/<int:pk>/', team_detail, name='team_detail'),
	path('teams/', by_teams, name='by_teams'),
	path('tracks/<int:pk>/', track_detail, name='track_detail'),
	path('tracks/', by_tracks, name='by_tracks'),
	path('<str:page>/', other_page, name='other'),
	path('', index, name='index'),
	]

main/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError
from captcha.fields import CaptchaField

from .models import AdvUser, user_registrated, Comment

class ChangeUserInfoForm(forms.ModelForm):
	"""Форма для изменения личных данных"""
	email = forms.EmailField(required=True, label='Адрес электронной почты')

	class Meta:
		model = AdvUser
		fields = ('username', 'email', 'first_name', 'last_name', 'send_messages', 'favorite_team')


class RegisterUserForm(forms.ModelForm):
	"""Форма для регистрации нового пользователя"""		
	email = forms.EmailField(required=True, label='Адрес электронной почты')
	password1 = forms.CharField(label='Пароль', widget = forms.PasswordInput,
								help_text=password_validation.password_validators_help_text_html())
	password2 = forms.CharField(label='Пароль(Повторно)', widget = forms.PasswordInput,
								help_text='Введите пароль еще раз')

	def clean_password1(self):
		"""валидация пароля первого поля"""
		password1 = self.cleaned_data['password1']
		if password1:
			password_validation.validate_password(password1)
		return password1	

	def clean(self):
		"""Проверка на идентичность обоих паролей"""
		super().clean()
		password1 = self.cleaned_data['password1']
		password2 = self.cleaned_data['password2']
		if password1 and password2 and password1 != password2:
			errors = {'password2': ValidationError('Введенные пароли не совпадают', code='password_mismatch')}
			raise ValidationError(errors)

	def save(self, commit=True):
		"""Сохранение пользователя"""
		user = super().save(commit=False)
		user.set_password(self.cleaned_data['password1'])
		# Активный пользователь?
		user.is_active = False
		# Выполнил ли пользователь процедуру активации?
		user.is_activated = False

		if commit:
			user.save()

		# отправка сигнала для отправки письма об активации
		user_registrated.send(RegisterUserForm, instance=user)

		return user	

	class Meta:
		model = AdvUser
		fields = ('username', 'email', 'password1', 'password2', 'first_name', 
				  'last_name', 'send_messages', 'favorite_team')	


class UserCommentForm(forms.ModelForm):
	"""Форма для занесения комментариев
		зарег. пользователям"""
	class Meta:
		model = Comment
		exclude = ('is_active',)
		widgets = {'driver' : forms.HiddenInput}


class GuestCommentForm(forms.ModelForm):
	"""Форма для занесения комментариев
		гостями"""		
	captcha = CaptchaField(label='Введите текст с картинки', 
							error_messages={'invalid':'Неправильный текст'})
	class Meta:
		model = Comment
		exclude = ('is_active',)
		widgets = {'driver' : forms.HiddenInput}							
		

main/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from django.template import TemplateDoesNotExist
from django.template.loader import get_template
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordResetDoneView
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView, PasswordResetCompleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import UpdateView, CreateView, DeleteView, FormView
from django.views.generic.base import TemplateView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.core.signing import BadSignature
from django.contrib.auth import logout
from django.contrib import messages
from django.core.paginator import Paginator
from django.views.decorators.cache import cache_page

from .models import AdvUser, Driver, Team, Track, Comment, Post
from .forms import ChangeUserInfoForm, RegisterUserForm, UserCommentForm, GuestCommentForm
from .utilities import signer
 



def index(request):
	"""Главная страница"""
	posts = Post.objects.all()[:10]
	drivers = Driver.objects.filter(is_active=True).order_by('-scores_season')
	teams = Team.objects.filter(is_active=True).order_by('-scores_season')
	context = {'posts': posts, 'drivers': drivers, 'teams': teams}
	return render(request, 'main/index.html', context)


def other_page(request, page):
	try:
		template = get_template('main/' + page + '.html')
	except TemplateDoesNotExist:
		raise Http404	
	return HttpResponse(template.render(request=request))	


class UserLoginView(LoginView):
	"""Странциа входа"""
	template_name = 'main/login.html'


# Декоратор
# Допускает к странице только пользователей,
# выполнивших вход
@login_required
def profile(request):
	"""Профиля"""
	return render(request, 'main/profile.html')


class UserLogoutView(LoginRequiredMixin, LogoutView):
	"""Выход с сайта"""
	template_name = 'main/logout.html'


class ChangeUserInfoView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
	"""Правки личных данных"""
	model = AdvUser
	template_name = 'main/change_user_info.html'
	form_class = ChangeUserInfoForm
	success_url = reverse_lazy('main:profile')
	success_message = 'Личные данные пользователя изменены'

	def dispatch(self, request, *args, **kwargs):
		self.user_id = request.user.pk
		return super().dispatch(request, *args, **kwargs)

	def get_object(self, queryset=None):
		if not queryset:
			queryset = self.get_queryset()
		return get_object_or_404(queryset, pk=self.user_id)	


class UserPasswordChangeView(SuccessMessageMixin, LoginRequiredMixin, PasswordChangeView):
	"""Изменения пароля"""
	template_name = 'main/password_change.html'
	success_url = reverse_lazy('main:profile')
	success_message = 'Пароль изменен'


class RegisterUserView(CreateView):
	"""Регистрации"""
	model = AdvUser
	template_name = 'main/register_user.html'
	form_class = RegisterUserForm
	success_url = reverse_lazy('main:register_done')


class RegisterDoneView(TemplateView):
	"""Сообщение об успешной регистрации"""	
	template_name = 'main/register_done.html'


def user_activate(request, sign):
	"""Активация нового пользователя"""
	try:
		username = signer.unsign(sign)
	except BadSignature:
		return render(request, 'main/bad_signature.html')
	user = get_object_or_404(AdvUser, username=username)
	
	if user.is_activated:
		template = 'main/user_is_activated.html'
	else:
		template = 'main/activation_done.html'
		user.is_active = True
		user.is_activated = True
		user.save()

	return render(request, template)		


class DeleteUserView(DeleteView):
	"""Удаление пользователя"""	
	model = AdvUser
	template_name = 'main/delete_user.html'
	success_url = reverse_lazy('main:index')

	def dispatch(self, request, *args, **kwargs):
		self.user_id = request.user.pk
		return super().dispatch(request, *args, **kwargs)

	def post(self, request, *args, **kwargs):
		logout(request)
		messages.add_message(request, messages.SUCCESS, 'Пользователь удален')
		return super().post(request, *args, **kwargs)

	def get_object(self, queryset=None):
		if not queryset:
			queryset = self.get_queryset()
		return get_object_or_404(queryset, pk=self.user_id)		


class UserPasswordResetView(PasswordResetView):
	"""Отправка письма для сброса пароля"""
	template_name = 'main/password_reset.html'
	subject_template_name = 'email/reset_subject.txt'
	email_template_name = 'email/reset_email.html'
	success_url = reverse_lazy('main:password_reset_done')
	

class UserPasswordResetDoneView(PasswordResetDoneView):
	"""Уведомление об отправке письма"""
	template_name = 'main/email_sent.html'


class UserPasswordResetConfirmView(PasswordResetConfirmView):
	"""Сброс пароля"""
	template_name = 'main/password_reset_confirm.html'
	success_url = reverse_lazy('main:password_reset_complete')


class UserPasswordResetCompleteView(PasswordResetCompleteView):
	"""Уведомление об успешной смене пароля"""
	template_name = 'main/password_reset_complete.html'



def by_drivers(request):
	"""Вывод всех пилотов"""
	drivers = Driver.objects.all()
	# Использование пагинатора
	paginator = Paginator(drivers, 8)
	if 'page' in request.GET:
		page_num = request.GET['page']
	else:
		page_num = 1
	page = paginator.get_page(page_num)

	context = {'page': page, 'drivers': page.object_list}
	return render(request, 'main/by_drivers.html', context)

# кеширование страницы 600 сек
@cache_page(600)
def by_teams(request):
	"""Вывод всех команд"""
	teams = Team.objects.all()
	context = {'teams': teams}
	return render(request, 'main/by_teams.html', context)



def by_tracks(request):
	"""Вывод всех трасс"""
	tracks = Track.objects.all()
	context = {'tracks': tracks}
	return render(request, 'main/by_tracks.html', context)



def team_detail(request, pk):
	"""Подробно о команде"""
	team = get_object_or_404(Team, pk=pk)
	drivers = Driver.objects.filter(team=pk)
	context = {'team': team, 'drivers': drivers}
	return render(request, 'main/team_detail.html', context)



def driver_detail(request, pk):
	"""Подробно о гонщике"""
	driver = get_object_or_404(Driver, pk=pk)
	comments = Comment.objects.filter(driver=pk, is_active=True)

	#заносим в поле driver ключ текущего пилота
	initial = {'driver': driver.pk}

	# Если пользователь авторизован, его имя заносим как автора коммментария
	if request.user.is_authenticated:
		initial['author'] = request.user.username
		form_class = UserCommentForm
	else:
		form_class = GuestCommentForm

	form = form_class(initial=initial)
	if request.method == 'POST':
		c_form = form_class(request.POST)
		if c_form.is_valid():
			c_form.save()
			messages.add_message(request, messages.SUCCESS, 'Комментарий добавлен')

		else:
			form = c_form
			messages.add_message(request, messages.WARNING, 'Комментарий не добавлен')

	context = {'driver': driver, 'comments': comments, 'form': form}
	return render(request, 'main/driver_detail.html', context)	
	


def track_detail(request, pk):
	"""Подробно о трассе"""
	track = get_object_or_404(Track, pk=pk)
	context = {'track': track}
	return render(request, 'main/track_detail.html', context)

main/templates/main/bad_signature.html
{% extends "layout/basic.html" %}


{% block title %}Ошибка активации{% endblock %}

{% block content %}

<h2>Активация</h2>
<p>При активации возникла ошибка</p>
<p><a href="{% url 'main:register' %}">Зарегистрироваться повторно</a></p>

{% endblock %}

main/templates/main/change_user_info.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %}Правка личных данных{% endblock %}

{% block content %}

<h2>Правка личных данных пользователя {{ user.username }}</h2>
<form method="post">
	{% csrf_token %}
	{% bootstrap_form form layout='horizontal' %}
	{% buttons submit='Сохранить' %}{% endbuttons %}
</form>

{% endblock %}

main/templates/main/delete_user.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %}Удаление пользователя{% endblock %}

{% block content %}

<h2>Удаление пользователя {{ object.username }}</h2>
<form method="post">
	{% csrf_token %}
	{% buttons submit='Удалить' %}{% endbuttons %}
</form>

{% endblock %}

main/templates/main/driver_detail.html
{% extends 'layout/basic.html' %}
{% load thumbnail %} 
{% load bootstrap4 %}
{% load static %}

{% block title %}{{ driver.first_name }} {{ driver.last_name }}{% endblock %}

{% block content %}

  <div class="card mb-3" style="max-width: 540px;">
    <div class="row no-gutters">
      <div class="col-md-4">
        <img src="{{ driver.image.url }}" class="card-img" alt="<>">
      </div>

      <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title">{{ driver.first_name }} {{ driver.last_name }}</h5>
            <p class="card-text">Дата рождения: {{ driver.date_of_birth }}</p>
            <p class="card-text">Возраст: {{ driver.age }}</p>
            <p class="card-text">Страна: {{ driver.country }}</p>
            <p class="card-text">Команда: {{ driver.team }}</p>
          </div>
      </div>
    </div>
  </div>

  <table class="table-sm table-bordered">
    <thead>
        <tr>
            <th scope="col">Гонок</th>
            <th scope="col">Побед</th>
            <th scope="col">Поулов</th>
            <th scope="col">Подиумов</th>
            <th scope="col">Лучших кругов</th>
            <th scope="col">Очков</th>
            <th scope="col">Побед в чемпионате</th>
        </tr>
    </thead>

    <tbody>
        <tr>
            <td>{{ driver.starts }}</td>
            <td>{{ driver.wins }}</td>
            <td>{{ driver.pole_position }}</td>
            <td>{{ driver.podiums }}</td>
            <td>{{ driver.best_laps }}</td>
            <td>{{ driver.scores }}</td>
            <td>{{ driver.championship_win }}</td>
        </tr>
    </tbody>
  </table>
  <p>*На момент окончания сезона 2020</p>


  <h3>Биография</h3>
  <p class="text-field">{{ driver.biography }}</p>

  <h4 class="mt-5">Новый комментарий</h4>
  <form method="post">
      <div class="col-7">
          {% csrf_token %}
          {% bootstrap_form form layout='horizontal'  %}
          {% buttons submit='Добавить' %}{% endbuttons %}
      </div>
 </form>

  {% if comments %}
      <div class="mt-5">

        {% for comment in comments %}
            <div class="my-2 p2 border">
                <h5>{{ comment.author }}</h5>
                <p>{{ comment.content }}</p>
                <p class="text-right font-italic">{{ comment.created_at }}</p> 
            </div>

        {% endfor %}
        
      </div>
  {% endif %}

{% endblock %}

main/templates/main/email_sent.html
{% extends "layout/basic.html" %}


{% block title %}Сброс пароля{% endblock %}

{% block content %}

<h2>Сброс пароля</h2>
<p>Добрый день!</p>
<p>Письмо отправлено на вашу электронную почту</p>

{% endblock %}

main/templates/main/index.html
{% extends 'layout/basic.html' %}
{% load static %}

{% block title %}Новости{% endblock %}


{% block content %}

	<div class="layer1">
		{% for post in posts %}
			<div class="feed ">
		  		<div class="feed-header">
					<h2>{{ post.title }}</h2>
				</div>

				<div class="feed-body">
			    	<blockquote class="blockquote mb-0">
			      	<p>{{ post.content }}</p>
			      	<footer class="blockquote-footer"><p>{{ post.author }} <p>{{ post.created_at }}</p> </p> </cite></footer>
			    	</blockquote>
				</div>
			</div>	
		{% endfor %}
	</div>

	<div class="layer2">
		<p class="table-result"><b>Личный зачет</b></p>

		<table class="table table-sm"  style="text-align: center;">
			<thead class="thead-dark">
				    <tr>
				      <th scope="col">Место</td>
				      <th scope="col">Имя</th>
				      <th scope="col">Фамилия</th>
				      <th scope="col">Очки</th>
				    </tr>
			</thead>

			<tbody class="thead-light">
				{% for driver in drivers %}
				
				    <tr class="table-secondary">
				    	<td scope="col">{{ forloop.counter }} </td>
				        <td scope="col" style="text-align: left;">{{ driver.first_name }}</td>
				        <td scope="col">{{ driver.last_name }}</td>
				        <td scope="col">{{ driver.scores_season }}</td>
				    </tr>
				    
				{% endfor %}  
			</tbody>
		</table>

		<p class="table-result"><b>Кубок конструкторов</b></p>

		<table class="table table-sm" style="text-align: center;">
			<thead class="thead-dark">
				    <tr>
				      <th scope="col">Место</th>
				      <th scope="col">Команда</th>
				      <th scope="col">Очки</th>
				    </tr>
			</thead>

			<tbody class="thead-light">
				{% for team in teams %}
				
				    <tr  class="table-secondary">
				    	<td scope="col">{{ forloop.counter }} </td>
				        <td scope="col">{{ team.name }}</td>
				        <td scope="col">{{ team.scores_season }}</td>
				    </tr>
				    
				{% endfor %}  
			</tbody>
		</table>

	</div>


	<div class="clear"></div>
{% endblock %}

main/templates/main/logout.html
{% extends "layout/basic.html" %}

{% block title %}Выход{% endblock %}

{% block content %}

<h2>Выход</h2>
<p>Вы успешно вышли с сайта</p>

{% endblock %}

main/templates/main/password_reset.html
{% extends "layout/basic.html" %}
{% load bootstrap4 %}

{% block title %}Сброс пароля{% endblock %}

{% block content %}
	<h2>Сброс пароля</h2>

	<form method="post">
		{% csrf_token %}
		{% bootstrap_form form layout='horizontal' %}
		{% buttons submit='Сбросить пароль' %}{% endbuttons %}
	</form>
	
{% endblock %}

main/templates/main/password_reset_confirm.html
{% extends "layout/basic.html" %}
{% load bootstrap4 %}

{% block title %}Сброс пароля{% endblock %}

{% block content %}

	<h2>Сброс пароля</h2>

	<form method="post">
		{% csrf_token %}
		{% bootstrap_form form layout='horizontal' %}
		{% buttons submit='Сменить пароль' %}{% endbuttons %}
	</form>

{% endblock %}

main/templates/main/profile.html
{% extends "layout/basic.html" %}


{% block title %}Профиль пользователя{% endblock %}

{% block content %}
	<h2>Профиль пользователя {{ user.username }}</h2>

	{% if user.first_name and user.last_name %}
		<p>Здраствуйте, {{ user.first_name }} {{ user.last_name }}!</p>

	{% else %}
		<p>Здраствуйте</p>

	{% endif %}
	
	<h3>Ваши комментарии</h3>

{% endblock %}

main/templates/main/register_done.html
{% extends "layout/basic.html" %}

{% block title %}Регистрация успешна{% endblock %}

{% block content %}

	<h2>Регистрация</h2>
	<p>Регистрация пользователя завершена</p>
	<p>Вы успешно зарегистрированы</p>
	<p>На адрес электронной почты отправлено письмо для активации</p>

{% endblock %}

main/templates/main/register_user.html
{% extends "layout/basic.html" %}
{% load bootstrap4 %}

{% block title %}Регистрация{% endblock %}

{% block content %}

	<h2>Регистрация пользователя</h2>

	<form method="post">
		{% csrf_token %}
		{% bootstrap_form form layout='horizontal' %}
		{% buttons submit='Зарегистрироваться' %}{% endbuttons %}
	</form>

{% endblock %}

main/templates/main/team_detail.html
{% extends 'layout/basic.html' %}
{% load thumbnail %} 
{% load bootstrap4 %}
{% load static %}

{% block title %}{{ team.name }}{% endblock %}

{% block content %}

    <h2 class="mb-2" style="text-align: center;">{{ team.name }}</h2>

    <div class="card mb-3">
        <img src="{{ team.team_car_image.url }}" class="card-img-top" alt="...">
        <div class="card-body">
            <p class="card-text"><b>Страна:</b> {{ team.country }}</p>
            <p class="card-text"><b>Дебют в Формуле 1:</b> {{ team.debut_in_f1 }}</p>
        </div>
    </div>

    <h4 style="text-align: center;">Пилоты</h4>

    {% if drivers %}
        <div class="d-flex justify-content-around">
            {% for driver in drivers %}
                <div class="card mb-3" style="max-width: 45%;">
                    <div class="row no-gutters">
                        <div class="col-md-4">
                            <img src="{{ driver.image.url }}" class="card-img" alt="<>">
                        </div>
                        
                        <div class="col-md-8">
                            <div class="card-body">
                                <h5 class="card-title">{{ driver.first_name }} {{ driver.last_name }}</a></h5>
                                <p class="card-text">Дата рождения: {{ driver.date_of_birth }}</p>
                                <p class="card-text">Страна: {{ driver.country }}</p>
                                <p class="card-text">Команда: {{ driver.team }}</p>
                                <p><a href="{% url 'main:driver_detail' pk=driver.pk %}">Подробнее</a></p>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endif %}

    <h5>Статистика команды</h5>

    <table class="table table-bordered">
        <thead>
            <tr>
                <th scope="col">Гонок</th>
                <th scope="col">Побед</th>
                <th scope="col">Поулов</th>
                <th scope="col">Подиумов</th>
                <th scope="col">Лучших кругов</th>
                <th scope="col">Очков</th>
                <th scope="col">Побед в КК*</th>
            </tr>
        </thead>

        <tbody>
            <tr>
                <td>{{ team.starts }}</td>
                <td>{{ team.wins }}</td>
                <td>{{ team.pole_position }}</td>
                <td>{{ team.podiums }}</td>
                <td>{{ team.best_laps }}</td>
                <td>{{ team.scores }}</td>
                <td>{{ team.constructors_win }}</td>
            </tr>
        </tbody>
    </table>

    <p>* КК - Кубок Конструкторов</p>
    <h5>История команды</h5>
    <p class="text-field">{{ team.team_history }}</p>

{% endblock %}

main/templates/main/track_detail.html
{% extends 'layout/basic.html' %}
{% load bootstrap4 %}
{% load static %}

{% block title %}{{ track.name }}{% endblock %}

{% block content %}

    <h1 class="track">{{ track.name }}</h1>
    <div class="text-center">
        <img src="{{ track.image.url }}"  style="max-width: 100%; height: auto;" class="rounded" alt="Изображение трассы">
    </div>

    <div>
        <h2>Характеристики трассы</h2>
        <ul>
            <li>Построена: <b>{{ track.build }}</b></li>
            <li>Расположение: <b>{{ track.located }}</b></li>
            <li>Длина трассы: <b>{{ track.length }} м.</b></li>
            <li>Средняя ширина трассы: <b>{{ track.width }} м.</b></li>
            <li>Движение: <b>{{ track.drive }}</b></li>
            <li>Количество поворотов: <b>{{ track.number_of_turns }}</b></li>
            <li>Рекорд трассы: <b>{{ track.record }} мин.</b></li>
        </ul>
    </div>

{% endblock %}